development: &dev
    adapter: sqlite3
    database: /home/serg/dnd/dnd.sqlite3
    pool: 50
    timeout: 5000

default_env:
    <<: *dev

heroku:
  adapter: pg
  encoding: unicode
  pool: 15
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
